services:
  backend:
    container_name: api
    command: dev
    build: .
    working_dir: /backend
    volumes:
      - ./src:/backend/src
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - 3001:3001
    tty: true
    stdin_open: true
    restart: always

  db:
    image: postgres
    shm_size: 128mb
    platform: linux/x86_64
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      timeout: 10s
      retries: 5
